name: CI/CD Pipeline

on:
  push:
    branches:
      - amazingfeature
  pull_request:
    branches:
      - amazingfeature

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter
        run: |
          pip install flake8
          flake8 .

      - name: Run type checking
        run: |
          pip install mypy
          mypy .

      - name: Run tests with coverage
        run: |
          pip install pytest-cov
          pytest --cov=.

      - name: Build Docker image
        run: |
          sudo docker build -t fastapi-app -f api/Dockerfile . --no-cache 

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Run the deploy job only if the test job succeeds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<your-ec2-public-ip> "
            cd /home/ubuntu/fastapi-book-project &&
            git pull origin amazingfeature &&
            sudo docker build -t fastapi-app -f api/Dockerfile . --no-cache && 
            sudo docker stop fastapi-container || true &&
            sudo docker rm fastapi-container || true &&
            sudo docker run -d -p 8000:8000 --name fastapi-container fastapi-app
          "
